### ISSUE TITLE
Feature Request: OpenKJ Songbook Agent - WAV support

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/SongbookAgent#5]
OpenKJ - All Windows and Mac versions
Windows 10
Mac OS 10.13.6 and 10.14

This is related to #131 ..... songbook agent also just needs to allow non-zipped WAV (and other audio format) files to be imported.

**Comment by coyote1357** [comment]
Fixed this a while ago.  No longer cares about the media files in the Songbook agent, since it doesn't know what hosting software may be being used or what media formats it may support.
